const Clothing=[
    { 
        id: 1,
        title: "Nautica Men's Short Sleeve Solid Crew Neck T-Shirt",
        description: "Slim fit t-shirt with a classic crew-neckline and comfortable cotton construction J class on chest",
        category: "T-Shirts", 
        price: 24.99, 
        size: ["S", "M", "L", "XL"], 
        color: ["black","navy","grey"], 
        material: "wool",
        images: ["https://i.pinimg.com/736x/6b/cb/4d/6bcb4d2aba5ca00af6934c316f0b9457.jpg","https://i.pinimg.com/736x/41/ed/66/41ed6626678d6d675ce220b5354588c3.jpg"], 
        availability: true, 
      }, 
      {
        id: 2,
        title: "INTO THE AM Mens T Shirt with Logo",
        description: "Slim BEST EVERYDAY TEE: These premium mens t-shirts are made from a high-quality fabric that's designed to keep you comfortable and looking great all day, every day. t-shirt with a classic crew-neckline and comfortable cotton construction J class on chest",
        category: "T-Shirts", 
        price: 24.95, 
        size: ["S", "M", "L", "XL"], 
        color: ["rgb(124, 204, 248)","rgb(215, 170, 125)","rgb(123, 102, 81)"], 
        material: "wool",
        images: ["https://i.pinimg.com/736x/44/4d/ff/444dffc42c878ee6bcaabcda083da5d2.jpg","https://i.pinimg.com/736x/7c/ce/47/7cce4792dc1ff06d7d328442a8e5483e.jpg","https://i.pinimg.com/736x/fe/25/31/fe2531389cb7231af72097c712342d7a.jpg"], 
        availability: true, 
      },
      {
        id: 3,
        title: "Calvin Klein Men's Cotton Classic 5-Pack Slim Undershirts",
        description: "LIGHTWEIGHT: Durable, 100% pure cotton fabric makes Calvin Klein’s t-shirts for men light and soft for all-day wear.",
        category: "T-Shirts", 
        price: 36.22, 
        size: ["S", "M", "L", "XL"], 
        color: ["White"], 
        material: "Cotton",
        images: ["https://i.pinimg.com/736x/26/37/82/263782a4ae5fad2a8c1345b4030c232b.jpg","https://i.pinimg.com/736x/d4/27/52/d427521fd51f7670ef7ff271e43d9f95.jpg"], 
        availability: true, 
      },
      {
        id: 4,
        title: "NITAGUT Mens Fashion Casual Front Placket Basic Long",
        description: "Fit - Slim / Snug Fit.US size.Model in size M.Model information(Height:185cm,Weight:183Ib,chest:102cm.",
        category: "T-Shirts", 
        price: 14.22, 
        size: ["S", "M", "L"], 
        color: ["blue"], 
        material: "Cotton",
        images: ["https://i.pinimg.com/736x/62/64/07/6264070fc55447df7fe002106e47e6b1.jpg","https://i.pinimg.com/736x/5a/7a/69/5a7a694cec09b49e76db2a09ab9d1859.jpg","https://i.pinimg.com/736x/44/ee/90/44ee90d3c87c844dd5d98ed93ea9b9e5.jpg"], 
        availability: true, 
      },
      {
        id: 5,
        title: "KLIEGOU Men's V Neck T Shirts",
        description: "Fabric: 95% Cotton 5% Polyester. Fabric technology: yarn-dyed blended. The pattern of the fabric is woven from threads of different colors. Advanced color. very beautiful. Do not fade.",
        category: "T-Shirts", 
        price: 19.99, 
        size: ["S", "L"], 
        color: ["Light Green"], 
        material: "Cotton",
        images: ["https://i.pinimg.com/736x/d3/ab/84/d3ab8442e4d14c53b24a664e24b33e4a.jpg","https://i.pinimg.com/736x/d3/b2/ac/d3b2ac7cb51f7e24703733e5c21c140f.jpg"], 
        availability: true, 
      },{
        id: 6,
        title: "FANARCHER Men’s Henley Short Sleeve T-Shirts",
        description: "65% cotton,35% polyester.Premium cotton polyester blend fabric.Soft to touch,comfortable with elasticity,lightweight, breathable, keep you relaxed and cool all the time.",
        category: "T-Shirts", 
        price: 19.99, 
        size: ["S","L"], 
        color: ["White"], 
        material: "Cotton",
        images: ["https://i.pinimg.com/736x/28/70/11/287011e0cb15437b7585b14fa969a629.jpg","https://i.pinimg.com/736x/92/a4/08/92a40831762920ab15a9cfe9b787c580.jpg"], 
        availability: true, 
      },{
        id: 7,
        title: "Premium Hoodies for Men S-4XL Lightweight Casual Fitted",
        description: "ULTRA-SOFT: Made from a poly-cotton blend, our mens hoodies feels buttery soft for all day comfort.",
        category: "Hoodies", 
        price: 20.99, 
        size: ["S","L","XL"], 
        color: ["rgb(22, 22, 141)","rgb(15, 93, 8)","rgb(37, 89, 203)"], 
        material: "polyester blend",
        images: ["https://i.pinimg.com/736x/23/14/ef/2314efd3aad51c216c4997bc16fcf109.jpg","https://i.pinimg.com/736x/cb/e4/5e/cbe45e62ee78759ba3b2b062213c2bbd.jpg","https://i.pinimg.com/736x/6e/ba/6f/6eba6fdfaa48b97dbec59b3d35d67dd0.jpg"], 
        availability: true, 
      },{
        id: 8,
        title: "Men's Novelty Color Block Pullover Hoodie",
        description: "Premium Material: Our men's hoodie features a soft and durable cotton+polyester blend, reducing pilling and shrinkage for long-lasting comfort.",
        category: "Hoodies", 
        price: 22.99, 
        size: ["S","L","XL"], 
        color: ["Olive Green"], 
        material: "cotton",
        images: ["https://i.pinimg.com/736x/ba/76/04/ba7604fdce68c44ec65a7bdd6431f953.jpg","https://i.pinimg.com/736x/26/f4/ec/26f4ecce5239a4f473f942cf89672202.jpg","https://i.pinimg.com/736x/d7/6b/07/d76b07cc3e6e5d62fac230003090a435.jpg"], 
        availability: true, 
      },{
        id: 9,
        title: "Gesean Men's Novelty Color Block Pullover Fleece Hoodie",
        description: "Inner Fabric: Weight 9 oz fleece with brushed interior offers exceptional softness and warmth with no shedding.",
        category: "Hoodies", 
        price: 30.99, 
        size: ["S","M","L","XL"], 
        color: ["Grey White Black"], 
        material: "cotton",
        images: ["https://i.pinimg.com/736x/bb/b9/83/bbb9832fc277d34ffca61949b42afdd7.jpg","https://i.pinimg.com/736x/f8/54/8b/f8548bf449a764b6153f816374f22729.jpg","https://i.pinimg.com/736x/f3/f1/5d/f3f15d1d3d26db4cd1f9f2bc40b32d84.jpg"], 
        availability: true, 
      },{
        id: 10,
        title: "Yundobop Men's Pullover Hoodies Amssy",
        description: "Size:US size,you can choose according to your normal size.It is our pleasure to serve you.",
        category: "Hoodies", 
        price: 20.99, 
        size: ["S","M","L","XL"], 
        color: ["Lightgrey/Grey"], 
        material: "cotton",
        images: ["https://i.pinimg.com/736x/15/bb/9c/15bb9cf16059fc305db0eefdec714fc2.jpg","https://i.pinimg.com/736x/4d/04/91/4d049170182ce11e1e45279f02b9f41f.jpg"], 
        availability: true, 
      },{
        id: 11,
        title: "COOFANDY Mens Hooded Coulde Cultures",
        description: "This mens hoodies pullover is made from soft and breathable fabric, delivering extraordinary comfort and warmth.",
        category: "Hoodies", 
        price: 24.99, 
        size: ["S","M","L","XL"], 
        color: ["Grey"], 
        material: "cotton",
        images: ["https://i.pinimg.com/736x/3c/3b/62/3c3b622525fc74e553a2a0e3336a48b7.jpg","https://i.pinimg.com/736x/3a/8d/2d/3a8d2dd711272234a086bb5db1b74a01.jpg"], 
        availability: true, 
      },{
        id: 12,
        title: "Gesean Men's Novelty Color Block Pullover Fleece Hoodie",
        description: "Inner Fabric: Weight 9 oz fleece with brushed interior offers exceptional softness and warmth with no shedding.",
        category: "Hoodies", 
        price: 23.99, 
        size: ["S","M","XL"], 
        color: ["Green"], 
        material: "wool",
        images: ["https://i.pinimg.com/736x/d5/94/2f/d5942f9e094bfb0f70a9cbf0c0a1f812.jpg","https://i.pinimg.com/736x/00/93/0f/00930fc323ffcee115553a7c68549e91.jpg"], 
        availability: true, 
      },{
        id: 13,
        title: "Men's Slim Fit Stretch Jeans",
        description: "Classic slim-fit jeans made with stretchable denim for all-day comfort and style.",
        category: "Jeans",
        price: 29.99,
        size: ["S", "M", "L", "XL"],
        color: ["Black"],
        material: "denim",
        images: ["https://m.media-amazon.com/images/I/5148sJ2wvNL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/51ah9UE-jML._AC_SX679_.jpg","https://m.media-amazon.com/images/I/51xq85+4XML._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 14,
        title: "Men's Straight Leg Classic Jeans",
        description: "Timeless straight-leg jeans with a relaxed fit for a versatile, casual look.",
        category: "Jeans",
        price: 32.50,
        size: ["M", "L", "XL"],
        color: ["Blue"],
        material: "denim",
        images: ["https://m.media-amazon.com/images/I/71r2P1Y3FNL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/81okh1-pirL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/81Cupzk9WnL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 15,
        title: "Men's Relaxed Fit Stretch Jeans",
        description: "Comfortable relaxed-fit jeans with added stretch for maximum mobility.",
        category: "Jeans",
        price: 27.99,
        size: ["S", "M", "L"],
        color: ["Dark blue"],
        material: "denim",
        images: ["https://m.media-amazon.com/images/I/71wfyZIUkqL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/71YVD3+vdEL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/71cbJlXciQL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 16,
        title: "Men's Distressed Skinny Jeans",
        description: "Trendy skinny-fit jeans with a distressed design for a modern, edgy style.",
        category: "Jeans",
        price: 34.99,
        size: ["M", "L", "XL"],
        color: ["Blue"],
        material: "denim",
        images: ["https://m.media-amazon.com/images/I/81xLtNzVb8L._AC_SX679_.jpg","https://m.media-amazon.com/images/I/91zAhn6H2uL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/81B+kSCkX6L._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 17,
        title: "Men's Bootcut Classic Denim Jeans",
        description: "Stylish bootcut jeans designed to fit comfortably over boots.",
        category: "Jeans",
        price: 31.49,
        size: ["S", "M", "L", "XL"],
        color: ["Blue"],
        material: "denim",
        images: ["https://m.media-amazon.com/images/I/81eFMjemnsL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/81mob4PhLNL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/81FrfWW-tYL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 18,
        title: "Men's Tapered Fit Casual Jeans",
        description: "Modern tapered-fit jeans offering a clean silhouette for casual outings.",
        category: "Jeans",
        price: 28.99,
        size: ["M", "L", "XL"],
        color: ["Black"],
        material: "denim",
        images: ["https://m.media-amazon.com/images/I/71uH+Og4SHL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/71VtrKEe-4L._AC_SX679_.jpg","https://m.media-amazon.com/images/I/71Gwo50ZxaL._AC_SX679_.jpg"],
        availability: true
      }, {
        id: 19,
        title: "Men's Slim Fit Stretch Chinos",
        description: "Tailored slim-fit chinos with a hint of stretch for a polished yet comfortable look.",
        category: "Chinos",
        price: 35.99,
        size: ["S", "M", "L", "XL"],
        color: ["Khaki Brown"],
        material: "cotton-blend",
        images: ["https://m.media-amazon.com/images/I/71De-IPZoeL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/71KUlX9CPvL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/81civFc2sjL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 20,
        title: "Men's Casual Straight-Leg Chinos",
        description: "Versatile straight-leg chinos designed for both work and casual outings.",
        category: "Chinos",
        price: 37.50,
        size: ["M", "L", "XL"],
        color: ["Black"],
        material: "cotton",
        images: ["https://m.media-amazon.com/images/I/71OR-bGAjeL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/71-+7ppMXrL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/71LxHJM0lXL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 21,
        title: "Men's Classic Fit Wrinkle-Free Chinos",
        description: "Classic-fit chinos crafted from wrinkle-free fabric for a sharp, all-day look.",
        category: "Chinos",
        price: 39.99,
        size: ["S", "M", "L"],
        color: ["Olive"],
        material: "cotton",
        images: ["https://m.media-amazon.com/images/I/71AeM8lRgfL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/61gMuK0DUyL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/91DixJZuW7L._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 22,
        title: "Men's Relaxed Fit Lightweight Chinos",
        description: "Lightweight and relaxed-fit chinos for everyday comfort and style.",
        category: "Chinos",
        price: 33.99,
        size: ["S", "M", "L", "XL"],
        color: ["Black"],
        material: "cotton-blend",
        images: ["https://m.media-amazon.com/images/I/51M4Zy+4w7L._AC_SY879_.jpg","https://m.media-amazon.com/images/I/51dRa6YktGL._AC_SY879_.jpg","https://m.media-amazon.com/images/I/61z6xmlMx2L._AC_SY879_.jpg"],
        availability: true
      },
      {
        id: 23,
        title: "Men's Tapered Stretch Chinos",
        description: "Modern tapered-fit chinos with added stretch for mobility and a sleek look.",
        category: "Chinos",
        price: 36.49,
        size: ["M", "L", "XL"],
        color: ["Stone"],
        material: "cotton-spandex",
        images: ["https://m.media-amazon.com/images/I/51sYGZzQOdL._AC_SY879_.jpg","https://m.media-amazon.com/images/I/51s5gGP9B8L._AC_SY879_.jpg","https://m.media-amazon.com/images/I/81Oa5EW5TEL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 24,
        title: "Men's Performance Flex Chinos",
        description: "Performance chinos with moisture-wicking fabric and a flexible fit for active days.",
        category: "Chinos",
        price: 40.99,
        size: ["S", "M", "L", "XL"],
        color: ["Black"],
        material: "poly-cotton blend",
        images: ["https://m.media-amazon.com/images/I/610BFJoMmsL._AC_SY879_.jpg","https://m.media-amazon.com/images/I/617hAghzNqL._AC_SY879_.jpg","https://m.media-amazon.com/images/I/61wLzzgE0bL._AC_SY879_.jpg"],
        availability: true
      },{
        id: 25,
        title: "Men's Classic Denim Jacket",
        description: "Timeless denim jacket with a comfortable fit, perfect for layering.",
        category: "Jackets",
        price: 49.99,
        size: ["S", "M", "L", "XL"],
        color: ["Black"],
        material: "denim",
        images: ["https://m.media-amazon.com/images/I/81iKppSUfrL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/81EzV7ajFRL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/81z+QSzJ-JL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 26,
        title: "Men's Lightweight Bomber Jacket",
        description: "Sleek bomber jacket with a lightweight design for casual outings.",
        category: "Jackets",
        price: 45.99,
        size: ["M", "L", "XL"],
        color: ["Coffee"],
        material: "polyester",
        images: ["https://i.pinimg.com/736x/38/8a/0f/388a0f7e1d92f89a19eb8e544a8b6757.jpg","https://i.pinimg.com/736x/52/31/ce/5231ceb3fb87f1853c7ec03a449845e0.jpg"],
        availability: true
      },
      {
        id: 27,
        title: "Men's Hooded Puffer Jacket",
        description: "Insulated hooded puffer jacket designed for warmth and style in cold weather.",
        category: "Jackets",
        price: 59.99,
        size: ["S", "M", "L"],
        color: ["Blue"],
        material: "polyester",
        images: ["https://m.media-amazon.com/images/I/91kBW3f583L._AC_SX679_.jpg","https://m.media-amazon.com/images/I/918toLK34vL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/91G1t9MQqpL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 28,
        title: "Men's Casual Utility Jacket",
        description: "Durable utility jacket with multiple pockets, ideal for everyday wear.",
        category: "Jackets",
        price: 54.99,
        size: ["M", "L", "XL"],
        color: ["Sky"],
        material: "cotton-blend",
        images: ["https://m.media-amazon.com/images/I/81AGBVroP3L._AC_SX679_.jpg","https://m.media-amazon.com/images/I/81jqHPnZ7ZL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/815u5RNqPQL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 29,
        title: "Men's Windbreaker Jacket",
        description: "Lightweight windbreaker jacket with water-resistant fabric for outdoor activities.",
        category: "Jackets",
        price: 39.99,
        size: ["S", "M", "L", "XL"],
        color: ["Gray"],
        material: "nylon",
        images: ["https://m.media-amazon.com/images/I/81UyE0wiikL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/71CLdEl0afL._AC_SX679_.jpg","https://m.media-amazon.com/images/I/819S1TxwCoL._AC_SX679_.jpg"],
        availability: true
      },
      {
        id: 30,
        title: "Men's Faux Leather Moto Jacket",
        description: "Stylish faux leather moto jacket with a slim fit and modern details.",
        category: "Jackets",
        price: 69.99,
        size: ["M", "L", "XL"],
        color: ["Green"],
        material: "faux leather",
        images: ["https://i.pinimg.com/736x/4a/67/8a/4a678a98c1060ebd3682f656ef92346e.jpg","https://i.pinimg.com/736x/2c/d0/62/2cd062e8ccf74e93d563bfb54bab65ff.jpg"],
        availability: true
      },{
        id: 31,
        title: "Men's Classic Low-Top Sneakers",
        description: "Stylish and comfortable low-top sneakers, perfect for everyday wear.",
        category: "Sneakers",
        price: 49.99,
        size: ["7", "8", "9", "10", "11", "12"],
        color: ["Tan Leather Burnsh"],
        material: "canvas",
        images: ["https://m.media-amazon.com/images/I/61DyKVaoHFL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/61Fq+h7HjBL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/51FBZ9sbjgL._AC_SY695_.jpg"],
        availability: true
      },
      {
        id: 32,
        title: "Men's High-Top Athletic Sneakers",
        description: "Durable high-top sneakers with enhanced ankle support for active lifestyles.",
        category: "Sneakers",
        price: 64.99,
        size: ["8", "9", "10", "11", "12"],
        color: ["Navy"],
        material: "canvas",
        images: ["https://m.media-amazon.com/images/I/71i2nhSJkkL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71dzsECOd7L._AC_SX695_.jpg","https://m.media-amazon.com/images/I/71N6-hmLhjL._AC_SX695_.jpg"],
        availability: true
      },
      {
        id: 33,
        title: "Men's Lightweight Running Sneakers",
        description: "Breathable and lightweight running sneakers designed for comfort and performance.",
        category: "Sneakers",
        price: 59.99,
        size: ["7", "8", "9", "10", "11"],
        color: [],
        material: "mesh",
        images: ["https://m.media-amazon.com/images/I/61sZZo0-pZL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/51LqfNL06WL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61OaBuptBkL._AC_SX695_.jpg"],
        availability: true
      },
      {
        id: 34,
        title: "Men's Slip-On Casual Sneakers",
        description: "Convenient slip-on sneakers with a minimalist design for casual outings.",
        category: "Sneakers",
        price: 44.99,
        size: ["8", "9", "10", "11", "12"],
        color: ["Gray"],
        material: "fabric",
        images: ["https://m.media-amazon.com/images/I/71C4-3Ksp-L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/71VJV4qjJyL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/81RMNp0cBoL._AC_SY695_.jpg"],
        availability: true
      },
      {
        id: 35,
        title: "Men's Retro Leather Sneakers",
        description: "Vintage-inspired leather sneakers with a modern twist for a stylish look.",
        category: "Sneakers",
        price: 69.99,
        size: ["7", "8", "9", "10", "11", "12"],
        color: ["Gray"],
        material: "leather",
        images: ["https://m.media-amazon.com/images/I/81jGP9IYOBL._AC_SX695_.jpg","https://m.media-amazon.com/images/I/51A23jr3uWL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/61NzhJ0pB4L._AC_SY695_.jpg"],
        availability: true
      },
      {
        id: 36,
        title: "Men's Cross-Training Sneakers",
        description: "Versatile cross-training sneakers built for workouts and all-day comfort.",
        category: "Sneakers",
        price: 54.99,
        size: ["8", "9", "10", "11"],
        color: ["Black"],
        material: "synthetic-mesh",
        images: ["https://m.media-amazon.com/images/I/711lA5rk08L._AC_SY695_.jpg","https://m.media-amazon.com/images/I/71cL-s+uiFL._AC_SY695_.jpg","https://m.media-amazon.com/images/I/71lG0nNNu7L._AC_SY695_.jpg"],
        availability: true
      }
]
export default Clothing